---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: infra-core-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.16.1
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true